### ISSUE TITLE
socket断线重连功能无效啊

### ISSUE THREAD

**Issue by battlesteed** [easemob/webim-weixin-xcx#5]
可以修复一下吗

**Comment by battlesteed** [comment]
自己动手,丰衣足食.自己修复了,还有一些问题也修复了.

**Comment by battlesteed** [comment]
还有一些问题,比如上线的时候收到一堆离线消息,由 于微信存储api wx.setStorage是异步的,导致部分消息丢失;在下也修复了.有需要的人可以找我要代码,靠官方半年过去了都不一定给回复呢

**Comment by gclsoft** [comment]
@battlesteed 能不能发我一份吗? qq 554933561 谢谢!

**Comment by yajore** [comment]
@battlesteed  我也遇到同样问题，如有时间请帮助一下 yajore@qq.com
