### ISSUE TITLE
uniapp 接入微信小程序sdk，登录后提示illegal buffer

### ISSUE THREAD

**Issue by supervergil** [easemob/webim-weixin-xcx#62]
微信小程序sdk 3.1.1

微信小程序开发工具提示错误信息：{type: 206}，并提示 illegal buffer，然后socket连接中断并提示{code: 1000, reason: "normal closure"}

错误信息和sdk报错位置见下图

![微信图片_20200514145003](https://user-images.githubusercontent.com/13966268/81902317-87ba9e00-95f2-11ea-803c-06b8fc4c6a59.png)

![微信图片_20200514145050](https://user-images.githubusercontent.com/13966268/81902322-8a1cf800-95f2-11ea-9226-2883779cbc14.png)

**Comment by myZhangDong** [comment]
是使用的这个项目里的sdk吗？ 运行这个项目报错吗

**Comment by supervergil** [comment]
是使用了项目中的sdk，版本3.1.1，项目本身没问题，但是接入uniapp中就报错了，不清楚是哪边的问题

**Comment by QWK-001** [comment]
@supervergil  你接入的这个uniapp是我们uniappDemo 还是你自己的demo

**Comment by QWK-001** [comment]
@supervergil  type:206 表示当前用户登陆了另一个设备 socketTask断连导致

**Comment by supervergil** [comment]
@QWK-001 目前跑得是自己的demo，我没看到你们提供的uniappDemo，如果有的话麻烦提供一下链接，我去看一下

**Comment by QWK-001** [comment]
@supervergil https://github.com/easemob/webim-uniapp-demo

**Comment by QWK-001** [comment]
@supervergil 那个问题我们自己的demo中也会出现，sdk会在下个版本中屏蔽这个报错，不影响正常业务逻辑。

**Comment by supervergil** [comment]
@QWK-001 我刚才重新跑了下，在微信小程序上报错确实没有影响，可以顺利运行，这个没问题了。

不过我尝试把小程序的sdk部署到app中，就会反复报illegal buffer的错误，并且阻塞了环信的所有业务流程。

从下图可以看出，尽管传入的参数是arrayBuffer类型，但是并没有进入上方的条件，而是一路走到了throw error中。

![微信截图_20200514200624](https://user-images.githubusercontent.com/13966268/81933016-3d9be180-961f-11ea-8469-84b11571faa6.png)

因为代码压缩过，我不知道具体的业务流程是什么，但是去掉上方的instanceof arrayBuffer判断条件，app中就能顺利跑起来。

个人推测可能是uni-app的运行环境导致的？希望你们有时间可以排查一下这个问题，虽然环信同样有苹果和安卓对应的sdk，但是对于普通开发者来说，显然更希望一套代码多端部署。

万分感谢！！

**Comment by QWK-001** [comment]
目前这个版本是只支持web端跟小程序的。




| |
前端求职简历--瞿伟康
邮箱：qwk_001@163.com
|

签名由 网易邮箱大师 定制

在2020年05月14日 20:19，张阳君 写道：

@QWK-001 我刚才重新跑了下，在微信小程序上报错确实没有影响，可以顺利运行，这个没问题了。

不过我尝试把小程序的sdk部署到app中，就会反复报illegal buffer的错误，并且阻塞了环信的所有业务流程。

从下图可以看出，尽管传入的参数是arrayBuffer类型，但是并没有进入上方的条件，而是一路走到了throw error中。

因为代码压缩过，我不知道具体的业务流程是什么，但是去掉上方的instanceof arrayBuffer判断条件，app中就能顺利跑起来。

个人推测可能是uni-app的运行环境导致的？希望你们有时间可以排查一下这个问题，虽然环信同样有苹果和安卓对应的sdk，但是对于普通开发者来说，显然更希望一套代码多端部署。

万分感谢！！

**Comment by QWK-001** [comment]
websdk的版本仅支持小程序跟web端目前没有支持app

**Comment by supervergil** [comment]
我这边修改sdk后已经修复了这个问题
