### ISSUE TITLE
comps/chat/chat]错误:  TypeError: Cannot set property 'rtc' of undefined

### ISSUE THREAD

**Issue by elias-1** [easemob/webim-weixin-xcx#77]
comps/chat/chat]错误:  TypeError: Cannot set property 'rtc' of undefined

**Comment by Wster11** [comment]
请提供复现分支和步骤

**Comment by elias-1** [comment]
我把代码复制进我的项目里了，然后去掉了login login_token  然后就报这个错了

**Comment by elias-1** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/7747400/218284738-34db9018-adbd-40b6-94d7-594c9028d05b.png">

**Comment by Wster11** [comment]
> <img alt="image" width="423" src="https://user-images.githubusercontent.com/7747400/218284738-34db9018-adbd-40b6-94d7-594c9028d05b.png">

看代码位置需要检查wx.WebIM.rtc， wx.WebIM是否存在

**Comment by elias-1** [comment]
另外我有个问题，您怎么看webrtc和matttemost
